// Auto-generated by inject_photos_from_json — do not edit manually
const allImages = import.meta.glob<{ default: string }>(
  '/src/assets/dac-construction/**/*.{jpg,jpeg,png}',
  { eager: true }
);

const folderMeta: Record<string, { title: string; category: string }> = {
  "feb-2024-project-6": {
    "title": "February 2024 Project",
    "category": "Work"
  },
  "another-year-comes-to-a": {
    "title": "Another Year Comes To A",
    "category": "Work"
  },
  "40-houses-underway-in-midleton": {
    "title": "40 Houses Underway In Midleton",
    "category": "Work"
  },
  "143-houses-well-underway-in": {
    "title": "143 Houses Well Underway In",
    "category": "Work"
  },
  "two-houses-tiled-on-monday": {
    "title": "Two Houses Tiled On Monday",
    "category": "Work"
  },
  "36-houses-completed-in-wicklow": {
    "title": "36 Houses Completed In Wicklow",
    "category": "Work"
  },
  "67-houses-completed-in-mulhuddart": {
    "title": "67 Houses Completed In Mulhuddart",
    "category": "Work"
  },
  "69-houses-completed-in-finglas": {
    "title": "69 Houses Completed In Finglas",
    "category": "Work"
  },
  "this-is-a-post-that": {
    "title": "This Is A Post That",
    "category": "Work"
  },
  "we-are-happy-to-have": {
    "title": "We Are Happy To Have",
    "category": "Work"
  },
  "40-units-underway-outside-wicklow": {
    "title": "40 Units Underway Outside Wicklow",
    "category": "Work"
  },
  "31-houses-well-under-way": {
    "title": "31 Houses Well Under Way",
    "category": "Work"
  },
  "6-seater-picnic-table-strong": {
    "title": "6 Seater Picnic Table Strong",
    "category": "Work"
  },
  "win-a-new-dac-3": {
    "title": "Win A New Dac 3",
    "category": "Work"
  },
  "win-a-new-dac-3-2": {
    "title": "Win A New Dac 3",
    "category": "Work"
  },
  "carnew-nursing-home-completed-in": {
    "title": "Carnew Nursing Home Completed In",
    "category": "Work"
  },
  "large-box-body-van-returning": {
    "title": "Large Box Body Van Returning",
    "category": "Work"
  },
  "check-out-our-new-machinery": {
    "title": "Check Out Our New Machinery",
    "category": "Work"
  },
  "check-out-our-new-stock": {
    "title": "Check Out Our New Stock",
    "category": "Work"
  },
  "check-out-the-start-of": {
    "title": "Check Out The Start Of",
    "category": "Work"
  },
  "30-houses-underway-in-carnew": {
    "title": "30 Houses Underway In Carnew",
    "category": "Work"
  },
  "8-luxurious-houses-in-blackrock": {
    "title": "8 Luxurious Houses In Blackrock",
    "category": "Work"
  },
  "20-houses-well-underway-in": {
    "title": "20 Houses Well Underway In",
    "category": "Work"
  },
  "new-extension-that-was-recently": {
    "title": "New Extension That Was Recently",
    "category": "Work"
  },
  "18-doors-framesdoors-and-architrave": {
    "title": "18 Doors Framesdoors And Architrave",
    "category": "Work"
  },
  "fibreglass-and-carpentry-job-in": {
    "title": "Fibreglass And Carpentry Job In",
    "category": "Work"
  },
  "fibre-glass-job-in-killurin": {
    "title": "Fibre Glass Job In Killurin",
    "category": "Work"
  },
  "a-job-we-did-2": {
    "title": "A Job We Did 2",
    "category": "Work"
  },
  "a-few-pictures-of-ballyboughal": {
    "title": "A Few Pictures Of Ballyboughal",
    "category": "Work"
  },
  "nearly-done-in-ballyboughal": {
    "title": "Nearly Done In Ballyboughal",
    "category": "Work"
  },
  "update-in-ballyboughal-slated-blocks": {
    "title": "Update In Ballyboughal Slated Blocks",
    "category": "Work"
  },
  "job-in-ballyboughal-new-build": {
    "title": "Job In Ballyboughal New Build",
    "category": "Work"
  }
};

export interface Project {
  id: string;
  title: string;
  category: string;
  coverImage: string;
  images: string[];
}

export const projects: Project[] = Object.entries(
  Object.groupBy(
    Object.entries(allImages).map(([path, mod]) => {
      const parts = path.split('/');
      const folder = parts[parts.length - 2];
      return { folder, src: mod.default };
    }),
    (item) => item.folder
  ) as Record<string, { folder: string; src: string }[]>
).map(([folder, items]) => ({
  id: folder,
  title: folderMeta[folder]?.title ?? folder.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
  category: folderMeta[folder]?.category ?? 'Work',
  coverImage: items[0]?.src ?? '',
  images: items.map(i => i.src),
}));

export const categories: string[] = ["Work"];
